apiVersion: v2
name: mychart
description: This chart is producing django sample app deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: ingress-nginx
  version: "4.1.0"
  repository: "https://kubernetes.github.io/ingress-nginx"
- name: cert-manager
  version: "1.8.0"
  namespace: cert-manager
  createNamespace: true
  repository: "https://charts.jetstack.io"
  installCRDs: true

