apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-fss-app
spec:
 storageClassName: oci-fss
 capacity:
  storage: 100Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
  server: {{.Values.mountTargetIp}}            
  path:   {{.Values.exportPathWeb | quote }}
  readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-fss-nginx
spec:
 storageClassName: oci-fss
 capacity:
  storage: 100Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
  server: {{.Values.mountTargetIp}}              
  path: {{.Values.exportPathNginx | quote }}         
  readOnly: false